version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME_STAGING
          requires:
            - build
          filters:
            branches:
              only: develop
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: 'cimg/node:14.15.1'
        environment:
          NODE_ENV: ci
          REACT_APP_API_URI: $REACT_APP_API_URI
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package-lock.json"}}
          paths:
            - node_modules
      - run: npm run test
